version = 0.1

[default.deploy.parameters]
stack_name = "fastapi-cicd-demo"
resolve_s3 = true
s3_prefix = "fastapi-cicd-demo"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "eu-north-1"
